<% if fog_file = File.expand_path('~/.fog') and File.exists?(fog_file)
  fog_file = YAML.load_file(fog_file)
  ENV['AWS_ACCESS_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_access_key_id']
  ENV['AWS_SECRET_ACCESS_KEY'] ||= fog_file.fetch('travis-ci', {})['aws_secret_access_key']
  ENV['AWS_KEYPAIR_NAME'] ||= fog_file.fetch('travis-ci', {})['aws_keypair_name']
  ENV['EC2_SSH_KEY_PATH'] ||= File.expand_path('~/.ssh/id_rsa_kitchen_ec2')
end %>
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  require_chef_omnibus: "11.4.4"

provisioner:
  name: chef_solo
  attributes:
    test_kitchen: true
    ebs_backups:
      user: ec2-user
      group: ec2-user
      aws:
        profiles:
          default:
            aws_access_key_id: 'EXAMPLE_KEY_1'
            aws_secret_access_key: 'EXAMPLE_SECRET_1'
            region: 'REGION_1'
            output: 'OUTPUT_1'
          user1:
            aws_access_key_id: 'EXAMPLE_KEY_2'
            aws_secret_access_key: 'EXAMPLE_SECRET_2'
            region: 'REGION_2'
            output: 'OUTPUT_2'
      crons:
        first:
          cron:
            minute: '1'
            weekday: '6'
          command:
            tag: 'Backups'
            purge_after_days: '30'
        before:
          cron:
            minute: '2'
            weekday: '6'
          command:
            before: 'land before time'
            tag: 'Before'
            purge_after_days: '30'
        after:
          cron:
            minute: '3'
            weekday: '6'
          command:
            after: 'happily ever after'
            tag: 'After'
            purge_after_days: '30'
        failure:
          cron:
            minute: '4'
            weekday: '6'
          command:
            failure: 'epic fail'
            tag: 'Failure'
            purge_after_days: '30'
        all:
          cron:
            minute: '5'
            weekday: '6'
          command:
            before: 'land before time'
            after: 'happily ever after'
            failure: 'epic fail'
            log: true
            tag: 'All'
            purge_after_days: '30'
        single_shared:
          cron:
            minute: '1'
            weekday: '6'
          command:
            tag: 'Backups'
            permitted_account_ids: 1234
        multi_shared:
          cron:
            minute: '1'
            weekday: '6'
          command:
            tag: 'Backups'
            permitted_account_ids: 1234 5678

platforms:
  - name: amazon-2014.10
    driver_plugin: ec2
    driver_config:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
      username: ec2-user
      flavor_id: c3.large
      image_id: ami-b66ed3de
      region: us-east-1
      availability_zone: us-east-1b
      security_group_ids: ['ci-testing']
      interface: public
      tags:
        Name: <%= "##{ENV['CI'] ? 'travis-ci' : ENV['USER']}-ebs_backups-kitchen" %>
        Env: public

suites:
  - name: default
    run_list:
      - recipe[ebs_backups::user]
      - recipe[ebs_backups::default]
    attributes:
