env:
  global:
  - EC2_SSH_KEY_PATH: ec2.pem
  - secure: ZSrOI/GM4qW6bNcziPiAjnqy7RoKj6igBaRpnTvBBINgjT+HWVy75fiIuowRq++uUhUUNcfkOeymZ2n2plgxEJlr2PZbMIOKX+qFuECiAbePdn0omkcm7eU62rmUVgnGSNIhns1P4B6Nt2NCiRXAAvdrTGmjS3LAMyZeEstSXEo=
  - secure: adLx1f0zynO7IX///Fs5z9HtUur+2gyyUtjU0yJ0YPMrxhFcTU/22H2CQ3rbJY8JGHj5YQUD4jmz2HW22YklLdC4NRWYeSZXGPBs9ILhzYZ4/JiQRgOIjz95k+tWnk2ZSWS72jMFXGdrN+4DOVbXQkZ+5gszEbwanbcJwLBloG8=
  - secure: nEQclN2LpUgqiNKnzn8DAjlrxVwaFfeN2eOYodiGmNES7sX4Cvq9VA5tswQPhkkLvsPRuEc6Y4ifs+6L1TOjRzmC1iUf/x6c6EU/FZTaRq+Lo7DO0ydG3k2bU9BHhl7dfRdjHkeM02SMfeOhTZuHzOePUaN7+MU0rfg70EWYjwA=
before_install:
- openssl aes-256-cbc -K $encrypted_8aeee3947bf2_key -iv $encrypted_8aeee3947bf2_iv
  -in id_rsa_kitchen_ec2.enc -out ~\/.ssh/id_rsa_kitchen_ec2 -d
- chmod 600 ec2.pem
script: bundle exec rake
language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
